# Generated by Django 3.0.8 on 2020-08-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='tipo',
            field=models.CharField(choices=[('A', 'Anual'), ('M', 'Mensual')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='programa',
            name='duracion',
            field=models.IntegerField(verbose_name='Duracion'),
        ),
    ]
