# Generated by Django 3.0.8 on 2020-08-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0004_auto_20200807_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='tipo',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
