# Generated by Django 3.0.8 on 2020-08-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0005_auto_20200807_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programa',
            name='tipo',
        ),
        migrations.AddField(
            model_name='programa',
            name='tipo_programa',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
