# Generated by Django 3.0.8 on 2020-08-07 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0006_auto_20200807_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programa',
            name='tipo_programa',
        ),
    ]
