# Generated by Django 3.0.8 on 2020-08-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0007_remove_programa_tipo_programa'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='tipo_programa',
            field=models.CharField(choices=[('A', 'Anual'), ('M', 'Mensual')], default=None, max_length=10),
        ),
    ]
