# Generated by Django 3.0.8 on 2020-08-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0008_programa_tipo_programa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programa',
            name='precio',
        ),
        migrations.AddField(
            model_name='programa',
            name='precio_matricula',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6, verbose_name='Valor Matricula'),
        ),
        migrations.AddField(
            model_name='programa',
            name='precio_pension',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6, verbose_name='Valor Pension'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='tipo_programa',
            field=models.CharField(choices=[('N', 'No definido'), ('A', 'Anual'), ('M', 'Mensual')], default=None, max_length=10, verbose_name='Modalidad Programa'),
        ),
    ]
