# Generated by Django 3.0.8 on 2020-08-07 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0009_auto_20200807_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('cod_materia', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Codigo Asignatura')),
                ('nombre_materia', models.CharField(max_length=70, verbose_name='Asignatura')),
                ('modalidad', models.CharField(choices=[('C', 'Creditos'), ('H', 'Horas')], max_length=10)),
                ('duracion', models.IntegerField()),
                ('estado', models.BooleanField()),
                ('cod_programa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Academico.Programa', verbose_name='Codigo Prograna')),
            ],
        ),
    ]
