# Generated by Django 3.0.8 on 2020-08-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0010_materia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
