# Generated by Django 3.0.8 on 2020-08-26 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0011_auto_20200818_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='cod_programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.Programa', verbose_name='Codigo Prograna'),
        ),
    ]
