# Generated by Django 3.0.8 on 2020-09-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0013_materia_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='cod_programa',
            field=models.CharField(max_length=10, unique=True, verbose_name='Codigo Prograna'),
        ),
    ]
