# Generated by Django 3.0.8 on 2021-04-20 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0014_auto_20200918_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valor_matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha Asignada')),
                ('valor_matricula_presencial', models.DecimalField(decimal_places=2, default=None, max_digits=6, verbose_name='Matricula ')),
                ('valor_matricula_online', models.DecimalField(decimal_places=2, default=None, max_digits=6, verbose_name='Valor Matricula')),
                ('cod_programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.Programa', verbose_name='Codigo Prograna')),
            ],
        ),
    ]
