# Generated by Django 3.0.8 on 2021-04-20 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0015_valor_matricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programa',
            name='precio_matricula',
        ),
        migrations.RemoveField(
            model_name='programa',
            name='precio_pension',
        ),
    ]
