# Generated by Django 3.0.8 on 2021-04-27 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0022_auto_20210421_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='materia_id',
            field=models.IntegerField(default=0, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
