# Generated by Django 3.0.8 on 2021-04-06 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0014_auto_20200918_1111'),
        ('Admision', '0004_auto_20200930_0135'),
        ('Matricula', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='ci',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='cod_programa',
        ),
        migrations.AddField(
            model_name='matricula',
            name='admision_id',
            field=models.ForeignKey(default=25, on_delete=django.db.models.deletion.CASCADE, to='Admision.admisione', verbose_name='Admisione'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matricula',
            name='materias',
            field=models.ManyToManyField(to='Academico.Materia'),
        ),
    ]
