# Generated by Django 3.0.8 on 2021-04-27 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matricula', '0002_auto_20210406_0055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matricula',
            old_name='nivel',
            new_name='id_matricula',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='materias',
        ),
        migrations.AddField(
            model_name='matricula',
            name='extesion',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='matricula',
            name='porcentaje_beca',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='fecha_matricula',
            field=models.DateField(default=None),
        ),
    ]
