# Generated by Django 3.0.8 on 2020-08-18 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Academico', '0011_auto_20200818_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experencia_espiritual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_conversion', models.DateField(verbose_name='Fecha de Conversion')),
                ('fecha_bautismo', models.DateField(verbose_name='Fecha Bautismo Agua')),
                ('bautismo_espiritual', models.BooleanField(verbose_name='Bautismo Espiritual')),
                ('fecha_bautismo_es', models.DateField(null=True, verbose_name='Bautismo Espiritual')),
                ('obra_señor', models.BooleanField(verbose_name='Llamamiento Obra Señor')),
                ('desc_obra', models.CharField(max_length=100, null=True, verbose_name='Obra Señor')),
                ('doctrinas', models.BooleanField(verbose_name='Doctrinas de Iglesia')),
                ('opinion', models.CharField(max_length=100, null=True, verbose_name='Necesidad Principal')),
                ('contribucion', models.CharField(max_length=100, null=True, verbose_name='Contribucion')),
                ('motivacion', models.CharField(max_length=100, null=True, verbose_name='Motivacion')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('ci', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Documento Identidad')),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('pais', models.CharField(max_length=20, null=True, verbose_name='Pais')),
                ('provincia', models.CharField(max_length=20, null=True, verbose_name='Provincia')),
                ('ciudad', models.CharField(max_length=20, null=True, verbose_name='Ciudad')),
                ('direccion', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('Instructor', 'Instructor'), ('Estudiante', 'Estudiante'), ('Administrativo', 'Administrativo')], default=None, max_length=15, verbose_name='Tipo Persona')),
                ('estado_c', models.CharField(choices=[('Soltero(a)', 'Soltero(a)'), ('Casado(a)', 'Casado(a)'), ('Divorciado(a)', 'Divorciado(a)'), ('Viudo(a)', 'Viudo(a)')], default=None, max_length=15, verbose_name='Estado Civil')),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.IntegerField(default=0, null=True)),
                ('telefono', models.CharField(max_length=14, null=True)),
                ('celular', models.CharField(max_length=14, null=True)),
                ('correo', models.EmailField(default=None, max_length=254)),
                ('cal_Emer', models.CharField(default='None', max_length=30, null=True)),
                ('emer_tele', models.CharField(default='0900000000', max_length=15, null=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default=None, max_length=10, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, verbose_name='Codigo Requisito')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Trasfondo_eclesiastico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iglesia', models.CharField(max_length=100, null=True, verbose_name='Iglesia Perteneciente')),
                ('denominacion', models.CharField(max_length=100, null=True, verbose_name='Denominacion')),
                ('direcion', models.CharField(max_length=200, null=True, verbose_name='Direccion Iglesia')),
                ('miembro', models.BooleanField(verbose_name='Miembro')),
                ('fecha_menbresia', models.DateField(null=True, verbose_name='Fecha Menbresia')),
                ('cargo_desempeñado', models.CharField(max_length=200, null=True, verbose_name='Cargos Desempeñados')),
                ('nom_apellido', models.CharField(max_length=70, null=True, verbose_name='Nombre y Apellido Pastor')),
            ],
        ),
        migrations.CreateModel(
            name='recomendaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=70, null=True, verbose_name='Nombre y Apellidos')),
                ('direccion', models.CharField(max_length=100, null=True, verbose_name='Direccion Domicilio')),
                ('telefono', models.CharField(max_length=11, null=True, verbose_name='telefono')),
                ('ci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admision.Persona', verbose_name='Referencia de')),
            ],
        ),
        migrations.CreateModel(
            name='estudios_realizado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Primarios', 'Primarios'), ('Secundarios', 'Secundarios'), ('Universitarios', 'Universitarios'), ('Religiosos', 'Religiosos'), ('Otros', 'Otros')], max_length=20, null=True, verbose_name='Tipo Estutdios')),
                ('fecha_ini', models.DateField(null=True, verbose_name='Fecha Inicio')),
                ('fecha_fin', models.DateField(null=True, verbose_name='Fecha Final')),
                ('institucion', models.CharField(max_length=100, null=True, verbose_name='Nombre Institucion')),
                ('graduacion', models.BooleanField(verbose_name='Graduacion')),
                ('ci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admision.Persona', verbose_name='Estudio de')),
            ],
        ),
        migrations.CreateModel(
            name='admisione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoAdmision', models.CharField(max_length=10, verbose_name='Codigo de Admision')),
                ('fecha', models.DateField(null=True, verbose_name='Fecha Solicitud')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='admision_images')),
                ('Programa', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='Academico.Programa', verbose_name='Programa Estudiar')),
                ('ci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admision.Persona', verbose_name='Cedula Admision')),
                ('id_estudios', models.ManyToManyField(to='Admision.estudios_realizado')),
                ('id_ex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admision.Experencia_espiritual', verbose_name='Id  Experiencia')),
                ('id_refecencia', models.ManyToManyField(to='Admision.recomendaciones')),
                ('id_requisito', models.ManyToManyField(to='Admision.Requisito')),
                ('id_tra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admision.Trasfondo_eclesiastico', verbose_name='Id Transfondo')),
            ],
        ),
    ]
