# Generated by Django 3.0.8 on 2020-09-04 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admision', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudios_realizado',
            old_name='tipo',
            new_name='tipo_est',
        ),
    ]
