# Generated by Django 3.0.8 on 2020-09-30 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0014_auto_20200918_1111'),
        ('Admision', '0002_auto_20200904_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='asignacionMaterias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_Asignacion', models.DateField(blank=True, null=True, verbose_name='Fecha Asignacion')),
                ('estado_asig', models.BooleanField()),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admision.Persona', verbose_name='Cedula Instructor')),
                ('materias', models.ManyToManyField(blank=True, null=True, to='Academico.Materia', verbose_name='')),
            ],
        ),
    ]
