# Generated by Django 3.0.8 on 2020-09-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0014_auto_20200918_1111'),
        ('Admision', '0003_asignacionmaterias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionmaterias',
            name='materias',
            field=models.ManyToManyField(to='Academico.Materia'),
        ),
    ]
