# Generated by Django 3.0.8 on 2020-08-18 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Matricula', '0001_initial'),
        ('Admision', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_pago', models.CharField(max_length=10, verbose_name='Codigo Pago')),
                ('Descripcion', models.CharField(choices=[('Matricula', 'Matricula'), ('Colegiatura', 'Colegiatura')], default=None, max_length=20)),
                ('obervaciones', models.CharField(max_length=100)),
                ('evidencia', models.ImageField(default=None, null=True, upload_to='vaucher_pago', verbose_name='Escaneado Vaucher')),
                ('estado', models.BooleanField(verbose_name='Estado del Pago')),
                ('fecha_pago', models.DateField(default=None, verbose_name='Fecha Generado Pago')),
                ('valor_pagar', models.DecimalField(decimal_places=2, default=None, max_digits=6, verbose_name='Valor a Pagar')),
                ('Valor_pagado', models.DecimalField(decimal_places=2, default=None, max_digits=6, verbose_name='Valor Pagado')),
                ('cod_matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Matricula.Matricula', verbose_name='Codigo Matricula')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admision.Persona', verbose_name='Codigo Estudiante')),
            ],
        ),
    ]
