# Generated by Django 3.0.8 on 2021-04-27 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pago', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pago',
            old_name='Descripcion',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='Valor_pagado',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='evidencia',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='fecha_pago',
        ),
        migrations.AddField(
            model_name='pago',
            name='fecha_generacion',
            field=models.DateField(default=None, verbose_name='Fecha Creado'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.BooleanField(verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='valor_pagar',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Valor a Pagar'),
        ),
        migrations.CreateModel(
            name='detalle_pagos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=None, verbose_name='Fecha Pago')),
                ('valor_cancelado', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Valor Cancelado')),
                ('Valor_pendiente', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Valor Pendiente')),
                ('evidencia', models.ImageField(default=None, null=True, upload_to='pagos/matricula', verbose_name='Respaldo')),
                ('pago_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pago.Pago', verbose_name='id_pago')),
            ],
        ),
    ]
